name: Manual ZIP Extract & Commit

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  unzip-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Unzip archive
        run: |
          unzip upload/*.zip -d extracted

      - name: Move files
        run: |
          cp -r extracted/* .
          rm -rf extracted

      - name: Remove zip
        run: rm -f upload/*.zip

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto extracted ZIP" || echo "No changes"
          git push
